In [4]:
import pm4py
import sys
sys.path.append('../../../TaskExecutionTimeMining/')
from event_log_transformer import *

In [5]:
file_path = '../../../../data/artificial_event_log_2_test.xes'
event_log = pm4py.read_xes(file_path)
event_log["id"] = event_log.index

parsing log, completed traces ::   0%|          | 0/892 [00:00<?, ?it/s]

In [6]:
event_log

,concept:name,lifecycle:transition,time:timestamp,org:resource,case:concept:name,id
0,DIAGNOSIS,SCHEDULE,2020-01-01 13:43:28.469233+00:00,None,0,0
1,DIAGNOSIS,START,2020-01-01 13:43:28.469233+00:00,Joe,0,1
2,DIAGNOSIS,COMPLETE,2020-01-01 14:59:41.608354+00:00,Joe,0,2
3,REPAIR,SCHEDULE,2020-01-01 14:59:41.608354+00:00,None,0,3
4,REPAIR,START,2020-01-01 14:59:41.608354+00:00,Jane,0,4
...,...,...,...,...,...,...
8023,REPAIR,START,2022-06-30 23:15:20.606227+00:00,Jane,891,8023
8024,REPAIR,COMPLETE,2022-07-01 07:28:48.982352+00:00,Jane,891,8024
8025,QUALITY_CONTROL,SCHEDULE,2022-07-01 07:28:48.982352+00:00,None,891,8025
8026,QUALITY_CONTROL,START,2022-07-01 07:28:48.982352+00:00,Karsten,891,8026
8027,QUALITY_CONTROL,COMPLETE,2022-07-01 10:28:54.472418+00:00,Karsten,891,8027

In [7]:
start_end_event_log = TransformEventLog.start_end_event_log(event_log)

/home/LordKunkler/TaskExecutionTimeMining/src/notebooks/standard/Artificial_Example/../../../TaskExecutionTimeMining/event_log_transformer.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  start_end_event_log.loc[:, 'duration'] = start_end_event_log[timestamp_name + '_complete'] - start_end_event_log[timestamp_name + '_start']
/home/LordKunkler/TaskExecutionTimeMining/src/notebooks/standard/Artificial_Example/../../../TaskExecutionTimeMining/event_log_transformer.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  start_end_event_log.loc[:, 'duration_seconds'] =  (start_end_event_log['duration']).astype('timedelta64[s]').astype(int)

In [8]:
# Seconds in day
start_end_event_log = TransformEventLog.seconds_in_day(start_end_event_log, 'time:timestamp_start')
start_end_event_log = TransformEventLog.day_of_week(start_end_event_log, 'time:timestamp_start')

In [9]:
start_end_event_log

,concept:name,lifecycle:transition_start,time:timestamp_start,org:resource,case:concept:name,id_start,lifecycle:transition_complete,time:timestamp_complete,id_complete,duration,duration_seconds,seconds_in_day,day_of_week
2,DIAGNOSIS,START,2020-01-01 13:43:28.469233+00:00,Joe,0,1,COMPLETE,2020-01-01 14:59:41.608354+00:00,2,0 days 01:16:13.139121,4573,49408,2
7,REPAIR,START,2020-01-01 14:59:41.608354+00:00,Jane,0,4,COMPLETE,2020-01-04 18:38:11.639016+00:00,5,3 days 03:38:30.030662,272310,53981,2
12,QUALITY_CONTROL,START,2020-01-04 18:38:11.639016+00:00,Jane,0,7,COMPLETE,2020-01-05 06:43:33.329583+00:00,8,0 days 12:05:21.690567,43521,67091,5
17,DIAGNOSIS,START,2020-01-01 19:33:48.900814+00:00,1,1,10,COMPLETE,2020-01-01 20:34:39.406353+00:00,11,0 days 01:00:50.505539,3650,70428,2
22,REPAIR,START,2020-01-01 20:34:39.406353+00:00,1,1,13,COMPLETE,2020-01-02 09:05:17.659036+00:00,14,0 days 12:30:38.252683,45038,74079,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
13357,REPAIR,START,2022-06-30 06:02:40.709625+00:00,Jane,890,8014,COMPLETE,2022-06-30 11:11:14.473595+00:00,8015,0 days 05:08:33.763970,18513,21760,3
13362,QUALITY_CONTROL,START,2022-06-30 11:11:14.473595+00:00,Jane,890,8017,COMPLETE,2022-06-30 13:45:04.355487+00:00,8018,0 days 02:33:49.881892,9229,40274,3
13367,DIAGNOSIS,START,2022-06-30 22:25:05.097535+00:00,Karsten,891,8020,COMPLETE,2022-06-30 23:15:20.606227+00:00,8021,0 days 00:50:15.508692,3015,80705,3
13372,REPAIR,START,2022-06-30 23:15:20.606227+00:00,Jane,891,8023,COMPLETE,2022-07-01 07:28:48.982352+00:00,8024,0 days 08:13:28.376125,29608,83720,3
13377,QUALITY_CONTROL,START,2022-07-01 07:28:48.982352+00:00,Karsten,891,8026,COMPLETE,2022-07-01 10:28:54.472418+00:00,8027,0 days 03:00:05.490066,10805,26928,4

In [10]:
# Resource counts
start_end_event_log = TransformEventLog.value_count_per_case_without_lifecycle(start_end_event_log,
                                                             column_name = 'concept:name',
                                                            case_name = 'case:concept:name',
                                                            timestamp_name = 'time:timestamp_start',
                                                            unique_id = 'id_start')
start_end_event_log = TransformEventLog.value_count_per_case_without_lifecycle(start_end_event_log,
                                                             column_name = 'org:resource',
                                                            case_name = 'case:concept:name',
                                                            timestamp_name = 'time:timestamp_start',
                                                            unique_id = 'id_start')
start_end_event_log = start_end_event_log.sort_values(by='time:timestamp_start')

In [11]:
start_end_event_log

,concept:name,lifecycle:transition_start,time:timestamp_start,org:resource,case:concept:name,id_start,lifecycle:transition_complete,time:timestamp_complete,id_complete,duration,...,seconds_in_day,day_of_week,DIAGNOSIS,QUALITY_CONTROL,REPAIR,1,Clark,Jane,Joe,Karsten
0,DIAGNOSIS,START,2020-01-01 13:43:28.469233+00:00,Joe,0,1,COMPLETE,2020-01-01 14:59:41.608354+00:00,2,0 days 01:16:13.139121,...,49408,2,1,0,0,0,0,0,1,0
1,REPAIR,START,2020-01-01 14:59:41.608354+00:00,Jane,0,4,COMPLETE,2020-01-04 18:38:11.639016+00:00,5,3 days 03:38:30.030662,...,53981,2,1,0,1,0,0,1,1,0
3,DIAGNOSIS,START,2020-01-01 19:33:48.900814+00:00,1,1,10,COMPLETE,2020-01-01 20:34:39.406353+00:00,11,0 days 01:00:50.505539,...,70428,2,1,0,0,1,0,0,0,0
4,REPAIR,START,2020-01-01 20:34:39.406353+00:00,1,1,13,COMPLETE,2020-01-02 09:05:17.659036+00:00,14,0 days 12:30:38.252683,...,74079,2,1,0,1,2,0,0,0,0
6,DIAGNOSIS,START,2020-01-02 07:47:21.536525+00:00,Clark,2,19,COMPLETE,2020-01-02 08:45:47.275476+00:00,20,0 days 00:58:25.738951,...,28041,3,1,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2672,QUALITY_CONTROL,START,2022-06-30 11:11:14.473595+00:00,Jane,890,8017,COMPLETE,2022-06-30 13:45:04.355487+00:00,8018,0 days 02:33:49.881892,...,40274,3,1,1,1,0,0,3,0,0
2669,QUALITY_CONTROL,START,2022-06-30 12:13:46.487067+00:00,Joe,889,8008,COMPLETE,2022-06-30 19:40:59.136223+00:00,8009,0 days 07:27:12.649156,...,44026,3,1,1,1,1,0,1,1,0
2673,DIAGNOSIS,START,2022-06-30 22:25:05.097535+00:00,Karsten,891,8020,COMPLETE,2022-06-30 23:15:20.606227+00:00,8021,0 days 00:50:15.508692,...,80705,3,1,0,0,0,0,0,0,1
2674,REPAIR,START,2022-06-30 23:15:20.606227+00:00,Jane,891,8023,COMPLETE,2022-07-01 07:28:48.982352+00:00,8024,0 days 08:13:28.376125,...,83720,3,1,0,1,0,0,1,0,1
2675,QUALITY_CONTROL,START,2022-07-01 07:28:48.982352+00:00,Karsten,891,8026,COMPLETE,2022-07-01 10:28:54.472418+00:00,8027,0 days 03:00:05.490066,...,26928,4,1,1,1,0,0,1,0,2

In [13]:
start_end_event_log.to_csv('../../transformed_event_logs/artificial_start_end_2_test.csv')
start_end_event_log.to_pickle('../../transformed_event_logs/artificial_start_end_2_test.pickle')