In [1]:
import pm4py
import sys
sys.path.append('../../../TaskExecutionTimeMining/')
from event_log_transformer import *

In [2]:
file_path = '../../../../data/artificial_event_log_2_train.xes'
event_log = pm4py.read_xes(file_path)
event_log["id"] = event_log.index

parsing log, completed traces ::   0%|          | 0/1802 [00:00<?, ?it/s]

In [3]:
event_log

,concept:name,lifecycle:transition,time:timestamp,org:resource,case:concept:name,id
0,DIAGNOSIS,SCHEDULE,2020-01-01 03:57:40.044121+00:00,None,0,0
1,DIAGNOSIS,START,2020-01-01 03:57:40.044121+00:00,Jane,0,1
2,DIAGNOSIS,COMPLETE,2020-01-01 04:34:23.549454+00:00,Jane,0,2
3,REPAIR,SCHEDULE,2020-01-01 04:34:23.549454+00:00,None,0,3
4,REPAIR,START,2020-01-01 04:34:23.549454+00:00,Joe,0,4
...,...,...,...,...,...,...
16209,DIAGNOSIS,SCHEDULE,2024-12-29 20:55:45.405475+00:00,None,1801,16209
16210,DIAGNOSIS,START,2024-12-29 20:55:45.405475+00:00,Joe,1801,16210
16211,DIAGNOSIS,COMPLETE,2024-12-29 22:15:50.349701+00:00,Joe,1801,16211
16212,REPAIR,SCHEDULE,2024-12-29 22:15:50.349701+00:00,None,1801,16212
16213,REPAIR,START,2024-12-29 22:15:50.349701+00:00,Joe,1801,16213

In [4]:
start_end_event_log = TransformEventLog.start_end_event_log(event_log)

/home/LordKunkler/TaskExecutionTimeMining/src/notebooks/eventlog_preprocessing/Artificial_Example/../../../TaskExecutionTimeMining/event_log_transformer.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  start_end_event_log.loc[:, 'duration'] = start_end_event_log[timestamp_name + '_complete'] - start_end_event_log[timestamp_name + '_start']
/home/LordKunkler/TaskExecutionTimeMining/src/notebooks/eventlog_preprocessing/Artificial_Example/../../../TaskExecutionTimeMining/event_log_transformer.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  start_end_event_log.loc[:, 'duration_seconds'] =  (start_end_event_log['duration']).astype('timedelta64[s]').astype(int)

In [5]:
# Seconds in day
start_end_event_log = TransformEventLog.seconds_in_day(start_end_event_log, 'time:timestamp_start')
start_end_event_log = TransformEventLog.day_of_week(start_end_event_log, 'time:timestamp_start')

In [6]:
start_end_event_log

,concept:name,lifecycle:transition_start,time:timestamp_start,org:resource,case:concept:name,id_start,lifecycle:transition_complete,time:timestamp_complete,id_complete,duration,duration_seconds,seconds_in_day,day_of_week
2,DIAGNOSIS,START,2020-01-01 03:57:40.044121+00:00,Jane,0,1,COMPLETE,2020-01-01 04:34:23.549454+00:00,2,0 days 00:36:43.505333,2203,14260,2
7,REPAIR,START,2020-01-01 04:34:23.549454+00:00,Joe,0,4,COMPLETE,2020-01-01 14:30:27.423999+00:00,5,0 days 09:56:03.874545,35763,16463,2
12,QUALITY_CONTROL,START,2020-01-01 14:30:27.423999+00:00,Joe,0,7,COMPLETE,2020-01-01 22:13:45.345445+00:00,8,0 days 07:43:17.921446,27797,52227,2
17,DIAGNOSIS,START,2020-01-01 08:16:35.844753+00:00,Jane,1,10,COMPLETE,2020-01-01 08:47:14.772217+00:00,11,0 days 00:30:38.927464,1838,29795,2
22,REPAIR,START,2020-01-01 08:47:14.772217+00:00,Karsten,1,13,COMPLETE,2020-01-01 13:27:22.316694+00:00,14,0 days 04:40:07.544477,16807,31634,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
26997,QUALITY_CONTROL,START,2024-12-26 19:03:41.622915+00:00,Joe,1799,16198,COMPLETE,2024-12-26 21:39:17.312456+00:00,16199,0 days 02:35:35.689541,9335,68621,3
27002,DIAGNOSIS,START,2024-12-26 18:05:59.540931+00:00,Clark,1800,16201,COMPLETE,2024-12-26 19:13:26.892809+00:00,16202,0 days 01:07:27.351878,4047,65159,3
27007,REPAIR,START,2024-12-26 19:13:26.892809+00:00,Clark,1800,16204,COMPLETE,2024-12-27 08:23:46.946760+00:00,16205,0 days 13:10:20.053951,47420,69206,3
27012,QUALITY_CONTROL,START,2024-12-27 08:23:46.946760+00:00,Jane,1800,16207,COMPLETE,2024-12-27 11:10:44.009123+00:00,16208,0 days 02:46:57.062363,10017,30226,4
27017,DIAGNOSIS,START,2024-12-29 20:55:45.405475+00:00,Joe,1801,16210,COMPLETE,2024-12-29 22:15:50.349701+00:00,16211,0 days 01:20:04.944226,4804,75345,6

In [7]:
# Resource counts
start_end_event_log = TransformEventLog.value_count_per_case_without_lifecycle(start_end_event_log,
                                                             column_name = 'concept:name',
                                                            case_name = 'case:concept:name',
                                                            timestamp_name = 'time:timestamp_start',
                                                            unique_id = 'id_start')
start_end_event_log = TransformEventLog.value_count_per_case_without_lifecycle(start_end_event_log,
                                                             column_name = 'org:resource',
                                                            case_name = 'case:concept:name',
                                                            timestamp_name = 'time:timestamp_start',
                                                            unique_id = 'id_start')
start_end_event_log = start_end_event_log.sort_values(by='time:timestamp_start')

In [8]:
start_end_event_log

,concept:name,lifecycle:transition_start,time:timestamp_start,org:resource,case:concept:name,id_start,lifecycle:transition_complete,time:timestamp_complete,id_complete,duration,...,seconds_in_day,day_of_week,DIAGNOSIS,QUALITY_CONTROL,REPAIR,1,Clark,Jane,Joe,Karsten
0,DIAGNOSIS,START,2020-01-01 03:57:40.044121+00:00,Jane,0,1,COMPLETE,2020-01-01 04:34:23.549454+00:00,2,0 days 00:36:43.505333,...,14260,2,1,0,0,0,0,1,0,0
1,REPAIR,START,2020-01-01 04:34:23.549454+00:00,Joe,0,4,COMPLETE,2020-01-01 14:30:27.423999+00:00,5,0 days 09:56:03.874545,...,16463,2,1,0,1,0,0,1,1,0
3,DIAGNOSIS,START,2020-01-01 08:16:35.844753+00:00,Jane,1,10,COMPLETE,2020-01-01 08:47:14.772217+00:00,11,0 days 00:30:38.927464,...,29795,2,1,0,0,0,0,1,0,0
4,REPAIR,START,2020-01-01 08:47:14.772217+00:00,Karsten,1,13,COMPLETE,2020-01-01 13:27:22.316694+00:00,14,0 days 04:40:07.544477,...,31634,2,1,0,1,0,0,1,0,1
5,QUALITY_CONTROL,START,2020-01-01 13:27:22.316694+00:00,Clark,1,16,COMPLETE,2020-01-01 17:21:42.825766+00:00,17,0 days 03:54:20.509072,...,48442,2,1,1,1,0,1,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5400,DIAGNOSIS,START,2024-12-26 18:05:59.540931+00:00,Clark,1800,16201,COMPLETE,2024-12-26 19:13:26.892809+00:00,16202,0 days 01:07:27.351878,...,65159,3,1,0,0,0,1,0,0,0
5399,QUALITY_CONTROL,START,2024-12-26 19:03:41.622915+00:00,Joe,1799,16198,COMPLETE,2024-12-26 21:39:17.312456+00:00,16199,0 days 02:35:35.689541,...,68621,3,1,1,1,1,0,0,1,1
5401,REPAIR,START,2024-12-26 19:13:26.892809+00:00,Clark,1800,16204,COMPLETE,2024-12-27 08:23:46.946760+00:00,16205,0 days 13:10:20.053951,...,69206,3,1,0,1,0,2,0,0,0
5402,QUALITY_CONTROL,START,2024-12-27 08:23:46.946760+00:00,Jane,1800,16207,COMPLETE,2024-12-27 11:10:44.009123+00:00,16208,0 days 02:46:57.062363,...,30226,4,1,1,1,0,2,1,0,0
5403,DIAGNOSIS,START,2024-12-29 20:55:45.405475+00:00,Joe,1801,16210,COMPLETE,2024-12-29 22:15:50.349701+00:00,16211,0 days 01:20:04.944226,...,75345,6,1,0,0,0,0,0,1,0

In [9]:
# inter-case information
inter_case_event_log = TransformEventLog.inter_instance_encoding_last_events(start_end_event_log,
                                case_name = 'case:concept:name',
                                timestamp_name = 'time:timestamp_start',
                                concept_name = 'concept:name',
                                state_prefix = 'intercase_n_1__',
                                n=1)

inter_case_event_log = TransformEventLog.inter_instance_encoding_last_events(inter_case_event_log,
                                case_name = 'case:concept:name',
                                timestamp_name = 'time:timestamp_start',
                                concept_name = 'concept:name',
                                state_prefix = 'intercase_n_3__',
                                n=3)

Counting unique states:   0%|          | 0/5404 [00:00<?, ?it/s]

Computing state counts:   0%|          | 0/5404 [00:00<?, ?it/s]

Counting unique states:   0%|          | 0/5404 [00:00<?, ?it/s]

Computing state counts:   0%|          | 0/5404 [00:00<?, ?it/s]

In [10]:
inter_case_event_log.to_csv('../../transformed_event_logs/artificial_start_end_2_train.csv')
inter_case_event_log.to_pickle('../../transformed_event_logs/artificial_start_end_2_train.pickle')