In [1]:
import pm4py
import sys
from pathlib import Path
import pandas

sys.path.append('../../TaskExecutionTimeMining/')
from event_log_transformer import *
pandas.set_option('display.max_columns', None)
pandas.set_option('display.max_rows', 200)

In [2]:
file_path = '../../../data/BPIC2015/'

xes_files = list(Path(file_path).rglob('*.xes'))

event_log = None
for xes_file in xes_files:
    print(f"Processing file: {xes_file}")
    # Read the XES file
    new_log = pm4py.read_xes(str(xes_file))
    
    if event_log is None:
        event_log = new_log
    else:
        event_log = pandas.concat([event_log, new_log], ignore_index=True)

Processing file: ../../../data/BPIC2015/BPIC15_2.xes

parsing log, completed traces ::   0%|          | 0/832 [00:00<?, ?it/s]

Processing file: ../../../data/BPIC2015/BPIC15_5.xes

parsing log, completed traces ::   0%|          | 0/1156 [00:00<?, ?it/s]

Processing file: ../../../data/BPIC2015/BPIC15_1.xes

parsing log, completed traces ::   0%|          | 0/1199 [00:00<?, ?it/s]

Processing file: ../../../data/BPIC2015/BPIC15_3.xes

parsing log, completed traces ::   0%|          | 0/1409 [00:00<?, ?it/s]

Processing file: ../../../data/BPIC2015/BPIC15_4.xes

parsing log, completed traces ::   0%|          | 0/1053 [00:00<?, ?it/s]

In [3]:
event_log.columns

Index(['monitoringResource', 'org:resource', 'activityNameNL', 'concept:name',
       'question', 'dateFinished', 'action_code', 'activityNameEN', 'planned',
       'lifecycle:transition', 'time:timestamp', 'case:Includes_subCases',
       'case:concept:name', 'case:Responsible_actor', 'case:endDate',
       'case:caseStatus', 'case:parts', 'case:caseProcedure',
       'case:last_phase', 'case:case_type', 'case:startDate',
       'case:requestComplete', 'case:SUMleges', 'case:IDofConceptCase',
       'case:termName', 'case:landRegisterID', 'dueDate', 'dateStop',
       'case:endDatePlanned'],
      dtype='object')

In [4]:
event_log = event_log.reset_index()
event_log['case_event_id'] = event_log.groupby('case:concept:name').cumcount()

#event_log = event_log[['index', 'case:concept:name', 'concept:name', 'activityNameEN', 'time:timestamp']]
event_log

,index,monitoringResource,org:resource,activityNameNL,concept:name,question,dateFinished,action_code,activityNameEN,planned,lifecycle:transition,time:timestamp,case:Includes_subCases,case:concept:name,case:Responsible_actor,case:endDate,case:caseStatus,case:parts,case:caseProcedure,case:last_phase,case:case_type,case:startDate,case:requestComplete,case:SUMleges,case:IDofConceptCase,case:termName,case:landRegisterID,dueDate,dateStop,case:endDatePlanned,case_event_id
0,0,4634935,560530,registratie datum binnenkomst aanvraag,01_HOOFD_010,EMPTY,2013-01-10 12:07:35,01_HOOFD_010,register submission date request,2012-03-23 10:21:14+00:00,complete,2012-03-21 00:00:00+00:00,J,10358444,4634935,2013-09-30 00:00:00+00:00,G,Milieu (vergunning),Uitgebreid,Zaak afgehandeld,557669,2012-03-21 00:00:00+00:00,FALSE,NaN,NaN,NaN,NaN,NaT,NaN,NaT,0
1,1,4634935,560530,OLO berichtenverkeer actief,01_HOOFD_011,False,2013-01-10 12:07:35,01_HOOFD_011,OLO messaging active,2012-03-23 10:26:05+00:00,complete,2012-03-22 10:26:08+00:00,J,10358444,4634935,2013-09-30 00:00:00+00:00,G,Milieu (vergunning),Uitgebreid,Zaak afgehandeld,557669,2012-03-21 00:00:00+00:00,FALSE,NaN,NaN,NaN,NaN,NaT,NaN,NaT,1
2,2,4634935,560530,versturen ontvangstbevestiging,01_HOOFD_020,True,2013-01-10 12:07:35,01_HOOFD_020,send confirmation receipt,NaT,complete,2012-03-22 10:26:08+00:00,J,10358444,4634935,2013-09-30 00:00:00+00:00,G,Milieu (vergunning),Uitgebreid,Zaak afgehandeld,557669,2012-03-21 00:00:00+00:00,FALSE,NaN,NaN,NaN,NaN,NaT,NaN,NaT,2
3,3,4634935,560530,fase aanvraag ontvangen,01_HOOFD_015,EMPTY,2013-01-10 12:07:35,01_HOOFD_015,phase application received,NaT,complete,2012-03-22 10:26:08+00:00,J,10358444,4634935,2013-09-30 00:00:00+00:00,G,Milieu (vergunning),Uitgebreid,Zaak afgehandeld,557669,2012-03-21 00:00:00+00:00,FALSE,NaN,NaN,NaN,NaN,NaT,NaN,NaT,3
4,4,4634935,560530,aanvrager is belanghebbende,03_GBH_005,True,2013-01-10 12:07:35,03_GBH_005,applicant is stakeholder,NaT,complete,2012-03-22 10:26:09+00:00,J,10358444,4634935,2013-09-30 00:00:00+00:00,G,Milieu (vergunning),Uitgebreid,Zaak afgehandeld,557669,2012-03-21 00:00:00+00:00,FALSE,NaN,NaN,NaN,NaN,NaT,NaN,NaT,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
262623,262623,560852,560781,invoeren verzenddatum beschikking,01_HOOFD_510_4,EMPTY,2014-09-10 00:00:00,01_HOOFD_510_4,enter senddate decision,2014-09-11 10:29:50+00:00,complete,2014-09-10 00:00:00+00:00,NaN,9968760,560852,2014-09-09 00:00:00+00:00,O,Bouw,NaN,Beschikking verzonden,557669,2014-07-29 00:00:00+00:00,TRUE,724.42365,9968787,Termijn bezwaar en beroep 1,NaN,NaT,NaN,NaT,37
262624,262624,560852,560781,afschrift beschikking omgevingsvergunning aan ...,01_HOOFD_510_1,EMPTY,2014-09-10 00:00:00,01_HOOFD_510_1,transcript decision environmental permit to st...,2014-09-10 11:41:24+00:00,complete,2014-09-10 00:00:00+00:00,NaN,9968760,560852,2014-09-09 00:00:00+00:00,O,Bouw,NaN,Beschikking verzonden,557669,2014-07-29 00:00:00+00:00,TRUE,724.42365,9968787,Termijn bezwaar en beroep 1,NaN,NaT,NaN,NaT,38
262625,262625,560852,560781,invoeren verzenddatum beschikking omgevingsver...,01_HOOFD_510_3,EMPTY,2014-09-10 00:00:00,01_HOOFD_510_3,enter senddate decision environmental permit,2014-09-11 10:29:50+00:00,complete,2014-09-10 00:00:00+00:00,NaN,9968760,560852,2014-09-09 00:00:00+00:00,O,Bouw,NaN,Beschikking verzonden,557669,2014-07-29 00:00:00+00:00,TRUE,724.42365,9968787,Termijn bezwaar en beroep 1,NaN,NaT,NaN,NaT,39
262626,262626,560852,560781,fase beschikking verzonden,01_HOOFD_515,EMPTY,2014-09-10 00:00:00,01_HOOFD_515,phase decision sent,2014-09-11 10:29:50+00:00,complete,2014-09-10 00:00:00+00:00,NaN,9968760,560852,2014-09-09 00:00:00+00:00,O,Bouw,NaN,Beschikking verzonden,557669,2014-07-29 00:00:00+00:00,TRUE,724.42365,9968787,Termijn bezwaar en beroep 1,NaN,NaT,NaN,NaT,40
262627,262627,560852,560781,invoeren verzenddatum beschikking omgevingsver...,01_HOOFD_510_2,EMPTY,2014-09-10 00:00:00,01_HOOFD_510_2,enter senddate decision environmental permit,2014-09-11 10:29:46+00:00,complete,2014-09-10 10:29:46+00:00,NaN,9968760,560852,2014-09-09 00:00:00+00:00,O,Bouw,NaN,Beschikking verzonden,557669,2014-07-29 00:00:00+00:00,TRUE,724.42365,9968787,Termijn bezwaar en beroep 1,NaN,NaT,NaN,NaT,41

In [5]:
event_log['lifecycle:transition'].unique()

array(['complete'], dtype=object)

In [6]:
start_end_event_log2 = TransformEventLog.start_end_event_log_next(event_log, merge_activity_on=['case:concept:name'], unique_column='index')
start_end_event_log2 = TransformEventLog.seconds_in_day(start_end_event_log2, 'time:timestamp_start')
start_end_event_log2 = TransformEventLog.day_of_week(start_end_event_log2, 'time:timestamp_start')

start_end_event_log2 = start_end_event_log2.sort_values(by=['case:concept:name', 'time:timestamp_start'])

In [7]:
start_end_event_log2[start_end_event_log2['case:concept:name'] == '10358444']

,index_start,monitoringResource_start,org:resource_start,activityNameNL_start,concept:name_start,question_start,dateFinished_start,action_code_start,activityNameEN_start,planned_start,lifecycle:transition_start,time:timestamp_start,case:Includes_subCases_start,case:concept:name,case:Responsible_actor_start,case:endDate_start,case:caseStatus_start,case:parts_start,case:caseProcedure_start,case:last_phase_start,case:case_type_start,case:startDate_start,case:requestComplete_start,case:SUMleges_start,case:IDofConceptCase_start,case:termName_start,case:landRegisterID_start,dueDate_start,dateStop_start,case:endDatePlanned_start,case_event_id_start,index_complete,monitoringResource_complete,org:resource_complete,activityNameNL_complete,concept:name_complete,question_complete,dateFinished_complete,action_code_complete,activityNameEN_complete,planned_complete,lifecycle:transition_complete,time:timestamp_complete,case:Includes_subCases_complete,case:Responsible_actor_complete,case:endDate_complete,case:caseStatus_complete,case:parts_complete,case:caseProcedure_complete,case:last_phase_complete,case:case_type_complete,case:startDate_complete,case:requestComplete_complete,case:SUMleges_complete,case:IDofConceptCase_complete,case:termName_complete,case:landRegisterID_complete,dueDate_complete,dateStop_complete,case:endDatePlanned_complete,case_event_id_complete,duration,duration_seconds,duration_ms,duration_hours,seconds_in_day,day_of_week
84,0,4634935,560530,registratie datum binnenkomst aanvraag,01_HOOFD_010,EMPTY,2013-01-10 12:07:35,01_HOOFD_010,register submission date request,2012-03-23 10:21:14+00:00,complete,2012-03-21 00:00:00+00:00,J,10358444,4634935,2013-09-30 00:00:00+00:00,G,Milieu (vergunning),Uitgebreid,Zaak afgehandeld,557669,2012-03-21 00:00:00+00:00,FALSE,NaN,NaN,NaN,NaN,NaT,NaN,NaT,0,1,4634935,560530,OLO berichtenverkeer actief,01_HOOFD_011,False,2013-01-10 12:07:35,01_HOOFD_011,OLO messaging active,2012-03-23 10:26:05+00:00,complete,2012-03-22 10:26:08+00:00,J,4634935,2013-09-30 00:00:00+00:00,G,Milieu (vergunning),Uitgebreid,Zaak afgehandeld,557669,2012-03-21 00:00:00+00:00,FALSE,NaN,NaN,NaN,NaN,NaT,NaN,NaT,1,1 days 10:26:08,123968.0,1.239680e+08,34.435556,0,2
337,1,4634935,560530,OLO berichtenverkeer actief,01_HOOFD_011,False,2013-01-10 12:07:35,01_HOOFD_011,OLO messaging active,2012-03-23 10:26:05+00:00,complete,2012-03-22 10:26:08+00:00,J,10358444,4634935,2013-09-30 00:00:00+00:00,G,Milieu (vergunning),Uitgebreid,Zaak afgehandeld,557669,2012-03-21 00:00:00+00:00,FALSE,NaN,NaN,NaN,NaN,NaT,NaN,NaT,1,4,4634935,560530,aanvrager is belanghebbende,03_GBH_005,True,2013-01-10 12:07:35,03_GBH_005,applicant is stakeholder,NaT,complete,2012-03-22 10:26:09+00:00,J,4634935,2013-09-30 00:00:00+00:00,G,Milieu (vergunning),Uitgebreid,Zaak afgehandeld,557669,2012-03-21 00:00:00+00:00,FALSE,NaN,NaN,NaN,NaN,NaT,NaN,NaT,4,0 days 00:00:01,1.0,1.000000e+03,0.000278,37568,3
338,2,4634935,560530,versturen ontvangstbevestiging,01_HOOFD_020,True,2013-01-10 12:07:35,01_HOOFD_020,send confirmation receipt,NaT,complete,2012-03-22 10:26:08+00:00,J,10358444,4634935,2013-09-30 00:00:00+00:00,G,Milieu (vergunning),Uitgebreid,Zaak afgehandeld,557669,2012-03-21 00:00:00+00:00,FALSE,NaN,NaN,NaN,NaN,NaT,NaN,NaT,2,4,4634935,560530,aanvrager is belanghebbende,03_GBH_005,True,2013-01-10 12:07:35,03_GBH_005,applicant is stakeholder,NaT,complete,2012-03-22 10:26:09+00:00,J,4634935,2013-09-30 00:00:00+00:00,G,Milieu (vergunning),Uitgebreid,Zaak afgehandeld,557669,2012-03-21 00:00:00+00:00,FALSE,NaN,NaN,NaN,NaN,NaT,NaN,NaT,4,0 days 00:00:01,1.0,1.000000e+03,0.000278,37568,3
339,3,4634935,560530,fase aanvraag ontvangen,01_HOOFD_015,EMPTY,2013-01-10 12:07:35,01_HOOFD_015,phase application received,NaT,complete,2012-03-22 10:26:08+00:00,J,10358444,4634935,2013-09-30 00:00:00+00:00,G,Milieu (vergunning),Uitgebreid,Zaak afgehandeld,557669,2012-03-21 00:00:00+00:00,FALSE,NaN,NaN,NaN,NaN,NaT,NaN,NaT,3,4,4634935,560530,aanvrager is belanghebbende,03_GBH_005,True,2013-01-10 12:07:35,03_GBH_005,applicant is stakeholder,NaT,complete,2012-03-22 10:26:09+00:00,J,4634935,2013-09-30 00:00:00+00:00,G,Milieu (vergunning),Uitgebreid,Zaak afgehandeld,557669,2012-03-21 00:00:00+00:00,FALSE,NaN,NaN,NaN,NaN,NaT,NaN,NaT,4,0 days 00:00:01,1.0,1.000000e+03,0.000278,37568,3
508,4,4634935,560530,aanvrager is belanghebbende,03_GBH_005,True,2013-01-10 12:07:35,03_GBH_005,applicant is stakeholder,NaT,complete,2012-03-22 10:26:09+00:00,J,10358444,4634935,2013-09-30 00:00:00+00:00,G,Milieu (vergunning),Uitgebreid,Zaak afgehandeld,557669,2012-03-21 00:00:00+00:00,FALSE,NaN,NaN,NaN,NaN,NaT,NaN,NaT,4,6,4634935,560530,invoeren verzenddatum ontvangstbevestiging,01_HOOFD_030_2,EMPTY,2013-01-10 12:07:35,01_HOOFD_030_2,enter senddate acknowledgement,2012-03-23 10:26:13+00:00,complete,2012-03-22 10:26:13+00:00,J,4634935,2013-09-30 00:00:00+00:00,G,Milieu (vergunning),Uitgebreid,Zaak afgehandeld,557669,2012-03-21 00:00:00+00:00,FALSE,NaN,NaN,NaN,NaN,NaT,NaN,NaT,6,0 days 00:00:04,4.0,4.000000e+03,0.001111,37569,3
509,5,4634935,560530,beeindigen op verzoek,05_EIND_010,False,2013-01-10 12:07:35,05_EIND_010,terminate on request,NaT,complete,2012-03-22 10:26:09+00:00,J,10358444,4634935,2013-09-30 00:00:00+00:00,G,Milieu (vergunning),Uitgebreid,Zaak afgehandeld,557669,2012-03-21 00:00:00+00:00,FALSE,NaN,NaN,NaN,NaN,NaT,NaN,NaT,5,6,4634935,560530,invoeren verzenddatum ontvangstbevestiging,01_HOOFD_030_2,EMPTY,2013-01-10 12:07:35,01_HOOFD_030_2,enter senddate acknowledgement,2012-03-23 10:26:13+00:00,complete,2012-03-22 10:26:13+00:00,J,4634935,2013-09-30 00:00:00+00:00,G,Milieu (vergunning),Uitgebreid,Zaak afgehandeld,557669,2012-03-21 00:00:00+00:00,FALSE,NaN,NaN,NaN,NaN,NaT,NaN,NaT,6,0 days 00:00:04,4.0,4.000000e+03,0.001111,37569,3
678,6,4634935,560530,invoeren verzenddatum ontvangstbevestiging,01_HOOFD_030_2,EMPTY,2013-01-10 12:07:35,01_HOOFD_030_2,enter senddate acknowledgement,2012-03-23 10:26:13+00:00,complete,2012-03-22 10:26:13+00:00,J,10358444,4634935,2013-09-30 00:00:00+00:00,G,Milieu (vergunning),Uitgebreid,Zaak afgehandeld,557669,2012-03-21 00:00:00+00:00,FALSE,NaN,NaN,NaN,NaN,NaT,NaN,NaT,6,8,4634935,560530,doorsturen aan bevoegd gezag,02_DRZ_010,False,2013-01-10 12:07:35,02_DRZ_010,forward to the competent authority,NaT,complete,2012-03-22 10:26:15+00:00,J,4634935,2013-09-30 00:00:00+00:00,G,Milieu (vergunning),Uitgebreid,Zaak afgehandeld,557669,2012-03-21 00:00:00+00:00,FALSE,NaN,NaN,NaN,NaN,NaT,NaN,NaT,8,0 days 00:00:02,2.0,2.000000e+03,0.000556,37573,3
679,7,4634935,560530,versturen ontvangstbevestiging,01_HOOFD_030_1,EMPTY,2013-01-10 12:07:35,01_HOOFD_030_1,send confirmation receipt,2012-03-23 10:26:08+00:00,complete,2012-03-22 10:26:13+00:00,J,10358444,4634935,2013-09-30 00:00:00+00:00,G,Milieu (vergunning),Uitgebreid,Zaak afgehandeld,557669,2012-03-21 00:00:00+00:00,FALSE,NaN,NaN,NaN,NaN,NaT,NaN,NaT,7,8,4634935,560530,doorsturen aan bevoegd gezag,02_DRZ_010,False,2013-01-10 12:07:35,02_DRZ_010,forward to the competent authority,NaT,complete,2012-03-22 10:26:15+00:00,J,4634935,2013-09-30 00:00:00+00:00,G,Milieu (vergunning),Uitgebreid,Zaak afgehandeld,557669,2012-03-21 00:00:00+00:00,FALSE,NaN,NaN,NaN,NaN,NaT,NaN,NaT,8,0 days 00:00:02,2.0,2.000000e+03,0.000556,37573,3
848,8,4634935,560530,doorsturen aan bevoegd gezag,02_DRZ_010,False,2013-01-10 12:07:35,02_DRZ_010,forward to the competent authority,NaT,complete,2012-03-22 10:26:15+00:00,J,10358444,4634935,2013-09-30 00:00:00+00:00,G,Milieu (vergunning),Uitgebreid,Zaak afgehandeld,557669,2012-03-21 00:00:00+00:00,FALSE,NaN,NaN,NaN,NaN,NaT,NaN,NaT,8,10,4634935,560530,reguliere procedure zonder MER,04_BPT_005,False,2013-01-10 12:07:35,04_BPT_005,regular procedure without MER,2012-03-23 10:26:15+00:00,complete,2012-03-22 10:26:21+00:00,J,4634935,2013-09-30 00:00:00+00:00,G,Milieu (vergunning),Uitgebreid,Zaak afgehandeld,557669,2012-03-21 00:00:00+00:00,FALSE,NaN,NaN,NaN,NaN,NaT,NaN,NaT,10,0 days 00:00:06,6.0,6.000000e+03,0.001667,37575,3
849,9,4634935,560530,BAG beheerder informeren,01_HOOFD_050,False,2013-01-10 12:07:35,01_HOOFD_050,inform BAG administrator,NaT,complete,2012-03-22 10:26:15+00:00,J,10358444,4634935,2013-09-30 00:00:00+00:00,G,Milieu (vergunning),Uitgebreid,Zaak afgehandeld,557669,2012-03-21 00:00:00+00:00,FALSE,NaN,NaN,NaN,NaN,NaT,NaN,NaT,9,10,4634935,560530,reguliere procedure zonder MER,04_BPT_005,False,2013-01-10 12:07:35,04_BPT_005,regular procedure without MER,2012-03-23 10:26:15+00:00,complete,2012-03-22 10:26:21+00:00,J,4634935,2013-09-30 00:00:00+00:00,G,Milieu (vergunning),Uitgebreid,Zaak afgehandeld,557669,2012-03-21 00:00:00+00:00,FALSE,NaN,NaN,NaN,NaN,NaT,NaN,NaT,10,0 days 00:00:06,6.0,6.000000e+03,0.001667,37575,3
1018,10,4634935,560530,reguliere procedure zonder MER,04_BPT_005,False,2013-01-10 12:07:35,04_BPT_005,regular procedure without MER,2012-03-23 10:26:15+00:00,complete,2012-03-22 10:26:21+00:00,J,10358444,4634935,2013-09-30 00:00:00+00:00,G,Milieu (vergunning),Uitgebreid,Zaak afgehandeld,557669,2012-03-21 00:00:00+00:00,FALSE,NaN,NaN,NaN,NaN,NaT,NaN,NaT,10,12,4634935,560530,activiteiten reguliere procedure,04_BPT_020,Uitgebreid,2013-01-10 12:07:35,04_BPT_020,activities regular procedure,2012-03-23 10:26:21+00:00,complete,2012-03-22 10:26:24+00:00,J,4634935,2013-09-30 00:00:00+00:00,G,Milieu (vergunning),Uitgebreid,Zaak afgehandeld,557669,2012-03-21 00:00:00+00:00,FALSE,NaN,NaN,NaN,NaN,NaT,NaN,NaT,12,0 days 00:00:03,3.0,3.000000e+03,0.000833,37581,3
1019,11,4634935,560530,MER aanwezig,04_BPT_010,False,2013-01-10 12:07:35,04_BPT_010,MER present,NaT,complete,2012-03-22 10:26:21+00:00,J,10358444,4634935,2013-09-30 00:00:00+00:00,G,Milieu (vergunning),Uitgebreid,Zaak afgehandeld,557669,2012-03-21 00:00:00+00:00,FALSE,NaN,NaN,NaN,NaN,NaT,NaN,NaT,11,12,4634935,560530,activiteiten reguliere procedure,04_BPT_020,Uitgebreid,2013-01-10 12:07:35,04_BPT_020,activities regular procedure,2012-03-23 10:26:21+00:00,complete,2012-03-22 10:26:24+00:00,J,4634935,2013-09-30 00:00:00+00:00,G,Milieu (vergunning),Uitgebreid,Zaak afgehandeld,557669,2012-03-21 00:00:00+00:00,FALSE,NaN,NaN,NaN,NaN,NaT,NaN,NaT,12,0 days 00:00:03,3.0,3.000000e+03,0.000833,37581,3
1188,12,4634935,560530,activiteiten reguliere procedure,04_BPT_020,Uitgebreid,2013-01-10 12:07:35,04_BPT_020,activities regular procedure,2012-03-23 10:26:21+00:00,complete,2012-03-22 10:26:24+00:00,J,10358444,4634935,2013-09-30 00:00:00+00:00,G,Milieu (vergunning),Uitgebreid,Zaak afgehandeld,557669,2012-03-21 00:00:00+00:00,FALSE,NaN,NaN,NaN,NaN,NaT,NaN,NaT,12,14,4634935,4634935,procedurebevestiging versturen,01_HOOFD_065_1,EMPTY,2013-01-10 12:07:35,01_HOOFD_065_1,send procedure confirmation,2012-03-23 10:26:25+00:00,complete,2012-12-19 09:43:57+00:00,J,4634935,2013-09-30 00:00:00+00:00,G,Milieu (vergunning),Uitgebreid,Zaak afgehandeld,557669,2012-03-21 00:00:00+00:00,FALSE,NaN,NaN,NaN,NaN,NaT,NaN,NaT,14,271 days 23:17:33,23498253.0,2.349825e+10,6527.292500,37584,3
1189,13,4634935,560530,gefaseerde aanvraag,04_BPT_030,False,2013-01-10 12:07:35,04_BPT_030,phased application,NaT,complete,2012-03-22 10:26:24+00:00,J,10358444,4634935,2013-09-30 00:00:00+00:00,G,Milieu (vergunning),Uitgebreid,Zaak afgehandeld,557669,2012-03-21 00:00:00+00:00,FALSE,NaN,NaN,NaN,NaN,NaT,NaN,NaT,13,14,4634935,4634935,procedurebevestiging versturen,01_HOOFD_065_1,EMPTY,2013-01-10 12:07:35,01_HOOFD_065_1,send procedure confirmation,2012-03-23 10:26:25+00:00,complete,2012-12-19 09:43:57+00:00,J,4634935,2013-09-30 00:00:00+00:00,G,Milieu (vergunning),Uitgebreid,Zaak afgehandeld,557669,2012-03-21 00:00:00+00:00,FALSE,NaN,NaN,NaN,NaN,NaT,NaN,NaT,14,271 days 23:17:33,23498253.0,2.349825e+10,6527.292500,37584,3
1358,14,4634935,4634935,procedurebevestiging versturen,01_HOOFD_065_1,EMPTY,2013-01-10 12:07:35,01_HOOFD_065_1,send procedure confirmation,2012-03-23 10:26:25+00:00,complete,2012-12-19 09:43:57+00:00,J,10358444,4634935,2013-09-30 00:00:00+00:00,G,Milieu (vergunning),Uitgebreid,Zaak afgehandeld,557669,2012-03-21 00:00:00+00:00,FALSE,NaN,NaN,NaN,NaN,NaT,NaN,NaT,14,16,4634935,4634935,publiceren,01_HOOFD_090,False,2013-01-10 12:07:35,01_HOOFD_090,publish,2012-12-20 09:44:52+00:00,complete,2012-12-19 09:44:52+00:00,J,4634935,2013-09-30 00:00:00+00:00,G,Milieu (vergunning),Uitgebreid,Zaak afgehandeld,557669,2012-03-21 00:00:00+00:00,FALSE,NaN,NaN,NaN,NaN,NaT,NaN,NaT,16,0 days 00:00:55,55.0,5.500000e+04,0.015278,35037,2
1359,15,4634935,4634935,invoeren verzenddatum procedurebevestiging,01_HOOFD_065_2,EMPTY,2013-01-10 12:07:35,01_HOOFD_065_2,enter senddate procedure confirmation,2012-12-20 09:43:57+00:00,complete,2012-12-19 09:43:57+00:00,J,10358444,4634935,2013-09-30 00:00:00+00:00,G,Milieu (vergunning),Uitgebreid,Zaak afgehandeld,557669,2012-03-21 00:00:00+00:00,FALSE,NaN,NaN,NaN,NaN,NaT,NaN,NaT,15,16,4634935,4634935,publiceren,01_HOOFD_090,False,2013-01-10 12:07:35,01_HOOFD_090,publish,2012-12-20 09:44:52+00:00,complete,2012-12-19 09:44:52+00:00,J,4634935,2013-09-30 00:00:00+00:00,G,Milieu (vergunning),Uitgebreid,Zaak afgehandeld,557669,2012-03-21 00:00:00+00:00,FALSE,NaN,NaN,NaN,NaN,NaT,NaN,NaT,16,0 days 00:00:55,55.0,5.500000e+04,0.015278,35037,2
1528,16,4634935,4634935,publiceren,01_HOOFD_090,False,2013-01-10 12:07:35,01_HOOFD_090,publish,2012-12-20 09:44:52+00:00,complete,2012-12-19 09:44:52+00:00,J,10358444,4634935,2013-09-30 00:00:00+00:00,G,Milieu (vergunning),Uitgebreid,Zaak afgehandeld,557669,2012-03-21 00:00:00+00:00,FALSE,NaN,NaN,NaN,NaN,NaT,NaN,NaT,16,18,4634935,4634935,behandelen deelzaken volledigheid,01_HOOFD_110_1,EMPTY,2013-01-10 12:07:35,01_HOOFD_110_1,treat subcases completeness,2012-12-20 09:44:52+00:00,complete,2012-12-19 09:46:37+00:00,J,4634935,2013-09-30 00:00:00+00:00,G,Milieu (vergunning),Uitgebreid,Zaak afgehandeld,557669,2012-03-21 00:00:00+00:00,FALSE,NaN,NaN,NaN,NaN,NaT,NaN,NaT,18,0 days 00:01:45,105.0,1.050000e+05,0.029167,35092,2
1529,17,4634935,4634935,WAW vergunningsaspect,01_HOOFD_130,False,2013-01-10 12:07:35,01_HOOFD_130,WAW permit aspect,2012-12-20 09:44:52+00:00,complete,2012-12-19 09:44:52+00:00,J,10358444,4634935,2013-09-30 00:00:00+00:00,G,Milieu (vergunning),Uitgebreid,Zaak afgehandeld,557669,2012-03-21 00:00:00+00:00,FALSE,NaN,NaN,NaN,NaN,NaT,NaN,NaT,17,18,4634935,4634935,behandelen deelzaken volledigheid,01_HOOFD_110_1,EMPTY,2013-01-10 12:07:35,01_HOOFD_110_1,treat subcases completeness,2012-12-20 09:44:52+00:00,complete,2012-12-19 09:46:37+00:00,J,4634935,2013-09-30 00:00:00+00:00,G,Milieu (vergunning),Uitgebreid,Zaak afgehandeld,557669,2012-03-21 00:00:00+00:00,FALSE,NaN,NaN,NaN,NaN,NaT,NaN,NaT,18,0 days 00:01:45,105.0,1.050000e+05,0.029167,35092,2
1614,18,4634935,4634935,behandelen deelzaken volledigheid,01_HOOFD_110_1,EMPTY,2013-01-10 12:07:35,01_HOOFD_110_1,treat subcases completeness,2012-12-20 09:44:52+00:00,complete,2012-12-19 09:46:37+00:00,J,10358444,4634935,2013-09-30 00:00:00+00:00,G,Milieu (vergunning),Uitgebreid,Zaak afgehandeld,557669,2012-03-21 00:00:00+00:00,FALSE,NaN,NaN,NaN,NaN,NaT,NaN,NaT,18,19,4634935,4634935,deelzaken volledigheid afgerond,01_HOOFD_110_2,EMPTY,2013-01-10 12:07:35,01_HOOFD_110_2,subcases completeness completed,2012-12-20 09:46:37+00:00,complete,2012-12-19 09:46:42+00:00,J,4634935,2013-09-30 00:00:00+00:00,G,Milieu (vergunning),Uitgebreid,Zaak afgehandeld,557669,2012-03-21 00:00:00+00:00,FALSE,NaN,NaN,NaN,NaN,NaT,NaN,NaT,19,0 days 00:00:05,5.0,5.000000e+03,0.001389,35197,2
1699,19,4634935,4634935,deelzaken volledigheid afgerond,01_HOOFD_110_2,EMPTY,2013-01-10 12:07:35,01_HOOFD_110_2,subcases completeness completed,2012-12-20 09:46:37+00:00,complete,2012-12-19 09:46:42+00:00,J,10358444,4634935,2013-09-30 00:00:00+00:00,G,Milieu (vergunning),Uitgebreid,Zaak afgehandeld,557669,2012-03-21 00:00:00+00:00,FALSE,NaN,NaN,NaN,NaN,NaT,NaN,NaT,19,20,4634935,4634935,procedure verandering,01_HOOFD_180,False,2013-01-10 12:07:35,01_HOOFD_180,procedure change,2012-12-20 09:46:42+00:00,complete,2012-12-19 09:46:43+00:00,J,4634935,2013-09-30 00:00:00+00:00,G,Milieu (vergunning),Uitgebreid,Zaak afgehandeld,557669,2012-03-21 00:00:00+00:00,FALSE,NaN,NaN,NaN,NaN,NaT,NaN,NaT,20,0 days 00:00:01,1.0,1.000000e+03,0.000278,35202,2
1784,20,4634935,4634935,procedure verandering,01_HOOFD_180,False,2013-01-10 12:07:35,01_HOOFD_180,procedure change,2012-12-20 09:46:42+00:00,complete,2012-12-19 09:46:43+00:00,J,10358444,4634935,2013-09-30 00:00:00+00:00,G,Milieu (vergunning),Uitgebreid,Zaak afgehandeld,557669,2012-03-21 00:00:00+00:00,FALSE,NaN,NaN,NaN,NaN,NaT,NaN,NaT,20,21,4634935,4634935,aanvraag volledig,08_AWB45_005,False,2013-01-10 12:07:35,08_AWB45_005,request complete,2012-12-20 09:46:43+00:00,complete,2012-12-19 09:46:49+00:00,J,4634935,2013-09-30 00:00:00+00:00,G,Milieu (vergunning),Uitgebreid,Zaak afgehandeld,557669,2012-03-21 00:00:00+00:00,FALSE,NaN,NaN,NaN,NaN,NaT,NaN,NaT,21,0 days 00:00:06,6.0,6.000000e+03,0.001667,35203,2
1869,21,4634935,4634935,aanvraag volledig,08_AWB45_005,False,2013-01-10 12:07:35,08_AWB45_005,request complete,2012-12-20 09:46:43+00:00,complete,2012-12-19 09:46:49+00:00,J,10358444,4634935,2013-09-30 00:00:00+00:00,G,Milieu (vergunning),Uitgebreid,Zaak afgehandeld,557669,2012-03-21 00:00:00+00:00,FALSE,NaN,NaN,NaN,NaN,NaT,NaN,NaT,21,22,4634935,4634935,termijn aanleveren ontbrekende gegevens,08_AWB45_010,42,2013-01-10 12:07:35,08_AWB45_010,term for supplying missing data,2012-12-20 09:46:49+00:00,complete,2012-12-19 09:47:00+00:00,J,4634935,2013-09-30 00:00:00+00:00,G,Milieu (vergunning),Uitgebreid,Zaak afgehandeld,557669,2012-03-21 00:00:00+00:00,FALSE,NaN,NaN,NaN,NaN,NaT,NaN,NaT,22,0 days 00:00:11,11.0,1.100000e+04,0.003056,35209,2
1954,22,4634935,4634935,termijn aanleveren ontbrekende gegevens,08_AWB45_010,42,2013-01-10 12:07:35,08_AWB45_010,term for supplying missing data,2012-12-20 09:46:49+00:00,complete,2012-12-19 09:47:00+00:00,J,10358444,4634935,2013-09-30 00:00:00+00:00,G,Milieu (vergunning),Uitgebreid,Zaak afgehandeld,557669,2012-03-21 00:00:00+00:00,FALSE,NaN,NaN,NaN,NaN,NaT,NaN,NaT,22,23,4634935,4634935,invoeren verzenddatum opvragen ontbrekende geg...,08_AWB45_020_2,EMPTY,2013-01-10 12:22:49,08_AWB45_020_2,enter senddate retrieve missing data,2013-01-11 12:08:08+00:00,complete,2013-01-10 00:00:00+00:00,J,4634935,2013-09-30 00:00:00+00:00,G,Milieu (vergunning),Uitgebreid,Zaak afgehandeld,557669,2012-03-21 00:00:00+00:00,FALSE,NaN,NaN,NaN,NaN,NaT,NaN,NaT,23,21 days 14:13:00,1865580.0,1.865580e+09,518.216667,35220,2
2039,23,4634935,4634935,invoeren verzenddatum opvragen ontbrekende geg...,08_AWB45_020_2,EMPTY,2013-01-10 12:22:49,08_AWB45_020_2,enter senddate retrieve missing data,2013-01-11 12:08:08+00:00,complete,2013-01-10 00:00:00+00:00,J,10358444,4634935,2013-09-30 00:00:00+00:00,G,Milieu (vergunning),Uitgebreid,Zaak afgehandeld,557669,2012-03-21 00:00:00+00:00,FALSE,NaN,NaN,NaN,NaN,NaT,NaN,NaT,23,24,4634935,4634935,opvragen ontbrekende gegevens,08_AWB45_020_1,EMPTY,2013-01-10 12:08:36,08_AWB45_020_1,retrieve missing data,2012-12-20 09:47:00+00:00,complete,2013-01-10 12:08:08+00:00,J,4634935,2013-09-30 00:00:00+00:00,G,Milieu (vergunning),Uitgebreid,Zaak afgehandeld,557669,2012-03-21 00:00:00+00:00,FALSE,NaN,NaN,NaN,NaN,NaT,NaN,NaT,24,0 days 12:08:08,43688.0,4.368800e+07,12.135556,0,3
2124,24,4634935,4634935,opvragen ontbrekende gegevens,08_AWB45_020_1,EMPTY,2013-01-10 12:08:36,08_AWB45_020_1,retrieve missing data,2012-12-20 09:47:00+00:00,complete,2013-01-10 12:08:08+00:00,J,10358444,4634935,2013-09-30 00:00:00+00:00,G,Milieu (vergunning),Uitgebreid,Zaak afgehandeld,557669,2012-03-21 00:00:00+00:00,FALSE,NaN,NaN,NaN,NaN,NaT,NaN,NaT,24,25,4634935,4634935,aanvullende gegevens ontvangen,08_AWB45_030,True,2013-02-14 14:28:45,08_AWB45_030,receive additional information,2013-01-11 12:08:41+00:00,complete,2013-02-14 14:28:34+00:00,J,4634935,2013-09-30 00:00:00+00:00,G,Milieu (vergunning),Uitgebreid,Zaak afgehandeld,557669,2012-03-21 00:00:00+00:00,FALSE,NaN,NaN,NaN,NaN,NaT,NaN,NaT,25,35 days 02:20:26,3032426.0,3.032426e+09,842.340556,43688,3

In [8]:
start_end_event_log2['case:concept:name'].unique().shape

(5644,)

In [9]:
start_end_event_log2.shape

(252767, 67)

In [10]:
train, test = pm4py.ml.split_train_test(start_end_event_log2)

In [11]:
print(train.shape, test.shape)
print(train['case:concept:name'].unique().shape, test['case:concept:name'].unique().shape)

(199793, 67) (52974, 67)
(4471,) (1173,)

In [12]:
train.to_csv('../transformed_event_logs/BPIC_2015_all_train.csv', index=False, date_format='%Y-%m-%d %H:%M:%S.%f')
train.to_pickle('../transformed_event_logs/BPIC_2015_all_train.pickle')

In [13]:
test.to_csv('../transformed_event_logs/BPIC_2015_all_test.csv', index=False, date_format='%Y-%m-%d %H:%M:%S.%f')
test.to_pickle('../transformed_event_logs/BPIC_2015_all_test.pickle')